name: GraalVM Native Image builds
on: [push, pull_request]
jobs:
  build:
    name: java-libpst on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
#        os: [macos-latest, windows-latest, ubuntu-latest]
      matrix:
        include:
          - os: windows-latest
            uploaded_filename: java-libpst.exe
            local_path: D:/a/java-libpst/java-libpst/target/

    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Example step using Maven plugin  # https://graalvm.github.io/native-build-tools/latest/maven-plugin.html
        run: mvn -Pnative package

#      - name: Download binary
#        uses: actions/download-artifact@v4
#        with:
#          name: java-libpst-${{ matrix.os }}
#          path: java-libpst *

      - name: Download binary
        uses: actions/upload-artifact@v4
        with:
          path: ${{ matrix.local_path }}
          name: ${{ matrix.uploaded_filename }}